CREATE	TABLE  AR_TABLE_GENERATOR(
	IID 		 					INTEGER,
  	GGEN_NAME 						VARCHAR(255) NOT NULL,
  	GGEN_VALUE 						VARCHAR(255),
  	PRIMARY KEY  (IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_INTEREST_MODEL(
	IID								INTEGER,
	TTOTAL							INTEGER,
	AACTION_FACTOR					DOUBLE,
	SSUSPENSE_FACTOR				DOUBLE,
	FFANTASY_FACTOR					DOUBLE,
	FFAMILY_FACTOR					DOUBLE,
	CCOMEDY_FACTOR					DOUBLE,
	AANIMATION_FACTOR				DOUBLE,
	AADVENTURE_FACTOR				DOUBLE,
	FFICTION_FACTOR					DOUBLE,
	CCHILD_FACTOR					DOUBLE,
	SSTORY_FACTOR					DOUBLE,
	LLOVE_FACTOR					DOUBLE,
	DDOCUMENT_FACTOR				DOUBLE,
	TTHRILLER_FACTOR				DOUBLE,
	CCRIME_FACTOR					DOUBLE,
	VVIDEO_FACTOR					DOUBLE,
	TTERROR_FACTOR					DOUBLE,
	WWAR_FACTOR						DOUBLE,
	WWEST_FACTOR					DOUBLE,
	MMUSIC_FACTOR					DOUBLE,
	SSPORT_FACTOR					DOUBLE,
	HHISTORY_FACTOR					DOUBLE,
	BBIOGRAPHY_FACTOR				DOUBLE,
	MMARTIAL_ARTS_FACTOR			DOUBLE,
	HHOMOSEXUAL_FACTOR				DOUBLE,
	PPHANTOM_FACTOR					DOUBLE,
	AANCIENT_COSTUME_FACTOR			DOUBLE,
	DDANCE_FACTOR					DOUBLE,
	SSEX_FACTOR						DOUBLE,
	AABSURD_FACTOR					DOUBLE,
	NNEWS_FACTOR					DOUBLE,
	BBLACK_FACTOR					DOUBLE,
	AADULT_FACTOR					DOUBLE,
	DDISASTER_FACTOR				DOUBLE,
	PRIMARY KEY (IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_USER(
	IID								INTEGER,
	IIP								VARCHAR(255),
	IINTEREST_MODEL_ID				INTEGER,
	PRIMARY KEY (IID)			
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_MOVIE(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	IIMAGE_URL						VARCHAR(255),	
	PPUBLISH_TIME					VARCHAR(255),
	DDESC							VARCHAR(255),
	UURL							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_STRATEGY(
	IID								INTEGER,
	PPUBLISH_START_DATE				VARCHAR(225),
	PPUBLISH_END_DATE				VARCHAR(225),
	SSTART_DAY_TIME					VARCHAR(225),
	EEND_DAY_TIME					VARCHAR(225),
	IIP_PREFIX						VARCHAR(225),
	PRIMARY KEY (IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_AD(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	IIMAGE_URL						VARCHAR(255),
	PPUBLISH_TIME					VARCHAR(255),
	DDESC							VARCHAR(255),
	UURL							VARCHAR(255),
	SSTRATEGY_ID					INTEGER,
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_ACTOR(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_ACTOR_AR_MOVIE(
	IID								INTEGER AUTO_INCREMENT,
	MOVIES_IID						INTEGER,
	ACTORS_IID						INTEGER,
	primary key(IID),
	foreign key(MOVIES_IID) references AR_MOVIE(IID),
	foreign key(ACTORS_IID) references AR_ACTOR(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_ACTOR_AR_AD(
	IID								INTEGER AUTO_INCREMENT,
	ADS_IID							INTEGER,
	ACTORS_IID						INTEGER,
	primary key(IID),
	foreign key(ADS_IID) references AR_AD(IID),
	foreign key(ACTORS_IID) references AR_ACTOR(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_TYPE(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_TYPE_AR_MOVIE(
	IID								INTEGER AUTO_INCREMENT,
	MOVIES_IID						INTEGER,
	TYPES_IID						INTEGER,
	primary key(IID),
	foreign key(MOVIES_IID) references AR_MOVIE(IID),
	foreign key(TYPES_IID) references AR_TYPE(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_TYPE_AR_AD(
	IID								INTEGER AUTO_INCREMENT,
	ADS_IID							INTEGER,
	TYPES_IID						INTEGER,
	primary key(IID),
	foreign key(ADS_IID) references AR_AD(IID),
	foreign key(TYPES_IID) references AR_TYPE(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_DIRECTOR(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_DIRECTOR_AR_MOVIE(
	IID								INTEGER AUTO_INCREMENT,
	MOVIES_IID						INTEGER,
	DIRECTORS_IID					INTEGER,
	primary key(IID),
	foreign key(MOVIES_IID) references AR_MOVIE(IID),
	foreign key(DIRECTORS_IID) references AR_DIRECTOR(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_DIRECTOR_AR_AD(
	IID								INTEGER AUTO_INCREMENT,
	ADS_IID							INTEGER,
	DIRECTORS_IID					INTEGER,
	primary key(IID),
	foreign key(ADS_IID) references AR_AD(IID),
	foreign key(DIRECTORS_IID) references AR_DIRECTOR(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_AREA(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_AREA_AR_MOVIE(
	IID								INTEGER AUTO_INCREMENT,
	MOVIES_IID						INTEGER,
	AREAS_IID						INTEGER,
	primary key(IID),
	foreign key(MOVIES_IID) references AR_MOVIE(IID),
	foreign key(AREAS_IID) references AR_AREA(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_AREA_AR_AD(
	IID								INTEGER AUTO_INCREMENT,
	ADS_IID							INTEGER,
	AREAS_IID						INTEGER,
	primary key(IID),
	foreign key(ADS_IID) references AR_AD(IID),
	foreign key(AREAS_IID) references AR_AREA(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_RECORD(
	IID								INTEGER,
	UUSER_ID						INTEGER,
	MMOVIE_ID						INTEGER,
	AAD_ID							INTEGER,
	TTIME							VARCHAR(255),
	AAD_RATE						INTEGER,
	MMOVIE_RATE						INTEGER,
	primary key(IID),			
	foreign key(UUSER_ID) references AR_USER(IID),
	foreign key(MMOVIE_ID) references AR_MOVIE(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AR_MOVIE_AD_SIMILARITY(
	IID								INTEGER,
	MMOVIE_ID						INTEGER,
	AAD_ID							INTEGER,
	SSIMILARITY						DOUBLE,
	primary key(IID),			
	foreign key(MMOVIE_ID) references AR_MOVIE(IID),
	foreign key(AAD_ID) references AR_AD(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;