CREATE	TABLE  CRAWLER_TABLE_GENERATOR(
	IID 		 					INTEGER,
  	GGEN_NAME 						VARCHAR(255) NOT NULL,
  	GGEN_VALUE 						VARCHAR(255),
  	PRIMARY KEY  (IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_USER(
	IID								INTEGER,
	IIP								VARCHAR(255),
	TTOTAL							INTEGER,
	AACTION_FACTOR					DOUBLE,
	SSUSPENSE_FACTOR				DOUBLE,
	FFANTASY_FACTOR					DOUBLE,
	FFAMILY_FACTOR					DOUBLE,
	CCOMEDY_FACTOR					DOUBLE,
	AANIMATION_FACTOR				DOUBLE,
	AADVENTURE_FACTOR				DOUBLE,
	FFICTION_FACTOR					DOUBLE,
	CCHILD_FACTOR					DOUBLE,
	SSTORY_FACTOR					DOUBLE,
	LLOVE_FACTOR					DOUBLE,
	DDOCUMENT_FACTOR				DOUBLE,
	TTHRILLER_FACTOR				DOUBLE,
	CCRIME_FACTOR					DOUBLE,
	VVIDEO_FACTOR					DOUBLE,
	TTERROR_FACTOR					DOUBLE,
	WWAR_FACTOR						DOUBLE,
	WWEST_FACTOR					DOUBLE,
	MMUSIC_FACTOR					DOUBLE,
	SSPORT_FACTOR					DOUBLE,
	HHISTORY_FACTOR					DOUBLE,
	BBIOGRAPHY_FACTOR				DOUBLE,
	MMARTIAL_ARTS_FACTOR			DOUBLE,
	HHOMOSEXUAL_FACTOR				DOUBLE,
	PPHANTOM_FACTOR					DOUBLE,
	AANCIENT_COSTUME_FACTOR			DOUBLE,
	DDANCE_FACTOR					DOUBLE,
	PRIMARY KEY (IID)			
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_MOVIE(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	IIMAGE_URL						VARCHAR(255),	
	AAREA							VARCHAR(255),
	PPUBLISH_TIME					VARCHAR(255),
	DDESC							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_AD(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	IIMAGE_URL						VARCHAR(255),	
	AAREA							VARCHAR(255),
	PPUBLISH_TIME					VARCHAR(255),
	DDESC							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_ACTOR(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_ACTOR_CRAWLER_MOVIE(
	IID								INTEGER AUTO_INCREMENT,
	MOVIES_IID						INTEGER,
	ACTORS_IID						INTEGER,
	primary key(IID),
	foreign key(MOVIES_IID) references CRAWLER_MOVIE(IID),
	foreign key(ACTORS_IID) references CRAWLER_ACTOR(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_ACTOR_CRAWLER_AD(
	IID								INTEGER AUTO_INCREMENT,
	ADS_IID							INTEGER,
	ACTORS_IID						INTEGER,
	primary key(IID),
	foreign key(ADS_IID) references CRAWLER_AD(IID),
	foreign key(ACTORS_IID) references CRAWLER_ACTOR(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_TYPE(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_TYPE_CRAWLER_MOVIE(
	IID								INTEGER AUTO_INCREMENT,
	MOVIES_IID						INTEGER,
	TYPES_IID						INTEGER,
	primary key(IID),
	foreign key(MOVIES_IID) references CRAWLER_MOVIE(IID),
	foreign key(TYPES_IID) references CRAWLER_TYPE(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_TYPE_CRAWLER_AD(
	IID								INTEGER AUTO_INCREMENT,
	ADS_IID							INTEGER,
	TYPES_IID						INTEGER,
	primary key(IID),
	foreign key(ADS_IID) references CRAWLER_AD(IID),
	foreign key(TYPES_IID) references CRAWLER_TYPE(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_DIRECTOR(
	IID								INTEGER,
	NNAME							VARCHAR(255),
	primary key(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_DIRECTOR_CRAWLER_MOVIE(
	IID								INTEGER AUTO_INCREMENT,
	MOVIES_IID						INTEGER,
	DIRECTORS_IID					INTEGER,
	primary key(IID),
	foreign key(MOVIES_IID) references CRAWLER_MOVIE(IID),
	foreign key(DIRECTORS_IID) references CRAWLER_DIRECTOR(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_DIRECTOR_CRAWLER_AD(
	IID								INTEGER AUTO_INCREMENT,
	ADS_IID							INTEGER,
	DIRECTORS_IID					INTEGER,
	primary key(IID),
	foreign key(ADS_IID) references CRAWLER_AD(IID),
	foreign key(DIRECTORS_IID) references CRAWLER_DIRECTOR(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_RECORD(
	IID								INTEGER,
	UUSER_ID						INTEGER,
	MMOVIE_ID						INTEGER,
	AAD_ID							INTEGER,
	TTIME							VARCHAR(255),
	AAD_RATE						INTEGER,
	MMOVIE_RATE						INTEGER,
	primary key(IID),			
	foreign key(UUSER_ID) references CRAWLER_USER(IID),
	foreign key(MMOVIE_ID) references CRAWLER_MOVIE(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CRAWLER_MOVIE_AD_SIMILARITY(
	IID								INTEGER,
	MMOVIE_ID						INTEGER,
	AAD_ID							INTEGER,
	SSIMILARITY						DOUBLE,
	primary key(IID),			
	foreign key(MMOVIE_ID) references CRAWLER_MOVIE(IID),
	foreign key(AAD_ID) references CRAWLER_AD(IID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;