DROP TABLE IF EXISTS AR_TABLE_GENERATOR;
DROP TABLE IF EXISTS AR_ACTOR_AR_MOVIE;
DROP TABLE IF EXISTS AR_TYPE_AR_MOVIE;
DROP TABLE IF EXISTS AR_DIRECTOR_AR_MOVIE;
DROP TABLE IF EXISTS AR_AREA_AR_MOVIE;

DROP TABLE IF EXISTS AR_ACTOR_AR_AD;
DROP TABLE IF EXISTS AR_TYPE_AR_AD;
DROP TABLE IF EXISTS AR_DIRECTOR_AR_AD;
DROP TABLE IF EXISTS AR_AREA_AR_AD;

DROP TABLE IF EXISTS AR_ACTOR;
DROP TABLE IF EXISTS AR_TYPE;
DROP TABLE IF EXISTS AR_DIRECTOR;
DROP TABLE IF EXISTS AR_AREA;

DROP TABLE IF EXISTS AR_RECORD;
DROP TABLE IF EXISTS AR_MOVIE_AD_SIMILARITY;

DROP TABLE IF EXISTS AR_MOVIE;
DROP TABLE IF EXISTS AR_AD;

DROP TABLE IF EXISTS AR_STRATEGY;

DROP TABLE IF EXISTS AR_USER;

DROP TABLE IF EXISTS AR_INTEREST_MODEL;