DROP TABLE IF EXISTS CRAWLER_TABLE_GENERATOR;
DROP TABLE IF EXISTS CRAWLER_ACTOR_CRAWLER_MOVIE;
DROP TABLE IF EXISTS CRAWLER_TYPE_CRAWLER_MOVIE;
DROP TABLE IF EXISTS CRAWLER_DIRECTOR_CRAWLER_MOVIE;

DROP TABLE IF EXISTS CRAWLER_ACTOR_CRAWLER_AD;
DROP TABLE IF EXISTS CRAWLER_TYPE_CRAWLER_AD;
DROP TABLE IF EXISTS CRAWLER_DIRECTOR_CRAWLER_AD;

DROP TABLE IF EXISTS CRAWLER_ACTOR;
DROP TABLE IF EXISTS CRAWLER_TYPE;
DROP TABLE IF EXISTS CRAWLER_DIRECTOR;

DROP TABLE IF EXISTS CRAWLER_RECORD;
DROP TABLE IF EXISTS CRAWLER_MOVIE_AD_SIMILARITY;

DROP TABLE IF EXISTS CRAWLER_MOVIE;
DROP TABLE IF EXISTS CRAWLER_AD;

DROP TABLE IF EXISTS CRAWLER_USER;