use ar;
set names gbk;

INSERT INTO CRAWLER_TABLE_GENERATOR(IID,GGEN_NAME,GGEN_VALUE) values(1,'CRAWLER_MOVIE_PK','1000000');
INSERT INTO CRAWLER_TABLE_GENERATOR(IID,GGEN_NAME,GGEN_VALUE) values(2,'CRAWLER_ACTOR_PK','1000000');
INSERT INTO CRAWLER_TABLE_GENERATOR(IID,GGEN_NAME,GGEN_VALUE) values(3,'CRAWLER_TYPE_PK','1000000');
INSERT INTO CRAWLER_TABLE_GENERATOR(IID,GGEN_NAME,GGEN_VALUE) values(4,'CRAWLER_DIRECTOR_PK','1000000');
INSERT INTO CRAWLER_TABLE_GENERATOR(IID,GGEN_NAME,GGEN_VALUE) values(5,'CRAWLER_USER_PK','1000000');
INSERT INTO CRAWLER_TABLE_GENERATOR(IID,GGEN_NAME,GGEN_VALUE) values(6,'CRAWLER_AD_PK','1000000');
INSERT INTO CRAWLER_TABLE_GENERATOR(IID,GGEN_NAME,GGEN_VALUE) values(7,'CRAWLER_RECORD_PK','1000000');
INSERT INTO CRAWLER_TABLE_GENERATOR(IID,GGEN_NAME,GGEN_VALUE) values(8,'CRAWLER_MOVIE_AD_SIMILARITY_PK','1000000');